import { useEffect } from "react";
import type { AgentArtifact, ArchitectureResult } from "@/lib/types";
import { MermaidDiagram } from "./mermaid-diagram";

type PrintableArchitectureReportProps = {
  result: ArchitectureResult;
  source: string;
  artifact?: AgentArtifact;
  onDiagramReady: () => void;
};

export function PrintableArchitectureReport({
  result,
  source,
  artifact,
  onDiagramReady,
}: PrintableArchitectureReportProps) {
  const architecture = result.applicationArchitecture;
  const hasDiagram = Boolean(architecture.mermaid.trim());

  useEffect(() => {
    if (!hasDiagram) onDiagramReady();
  }, [hasDiagram, onDiagramReady]);

  return (
    <article className="print-report">
      <header className="pdf-doc-header">
        <div className="pdf-brand">
          <span className="pdf-brand-mark" aria-hidden="true">AG</span>
          <span>ArcGate AI</span>
          <span className="pdf-brand-subtitle">Governed architecture studio</span>
        </div>
        <p className="pdf-kicker">Solution architecture package</p>
        <p className={`pdf-status ${artifact ? "pdf-status-approved" : "pdf-status-draft"}`}>
          {artifact ? "Approved package" : "Draft · For architecture review"}
        </p>
        <h1 className="pdf-title">{result.title}</h1>
        <p className="pdf-meta">Generated by ArcGate AI with OpenAI ({source}).</p>
      </header>

      <section className="pdf-section">
        <h2 className="pdf-section-title">Proposed solution</h2>
        <p className="pdf-lead">{result.proposedSolution}</p>
      </section>

      <section className="pdf-section">
        <h2 className="pdf-section-title">Application architecture</h2>
        <p className="pdf-subtitle">
          <strong>Style:</strong> {architecture.style}
          {architecture.styleId ? ` (${architecture.styleId})` : ""}
        </p>
        {architecture.styleRationale ? (
          <p className="pdf-copy"><strong>Why this style:</strong> {architecture.styleRationale}</p>
        ) : null}
        <p className="pdf-copy">{architecture.overview}</p>
        <p className="pdf-copy"><strong>Data flow:</strong> {architecture.dataFlow}</p>
      </section>

      {hasDiagram ? (
        <section className="pdf-section pdf-diagram-section">
          <h2 className="pdf-section-title">Architecture diagram</h2>
          <div className="pdf-diagram">
            <MermaidDiagram
              chart={architecture.mermaid}
              forceLight
              onReady={onDiagramReady}
            />
          </div>
        </section>
      ) : null}

      <section className="pdf-section">
        <h2 className="pdf-section-title">Application layers</h2>
        <table className="pdf-table">
          <thead>
            <tr><th>Layer</th><th>Responsibilities</th><th>Components</th></tr>
          </thead>
          <tbody>
            {architecture.layers.length ? architecture.layers.map((layer) => (
              <tr key={layer.name}>
                <td><strong>{layer.name}</strong></td>
                <td>{layer.responsibilities}</td>
                <td>{layer.components.join(", ") || "No components listed"}</td>
              </tr>
            )) : (
              <tr><td colSpan={3}>No application layers captured.</td></tr>
            )}
          </tbody>
        </table>
      </section>

      <section className="pdf-section">
        <h2 className="pdf-section-title">Application modules</h2>
        <table className="pdf-table">
          <thead>
            <tr><th>Module</th><th>Layer</th><th>Responsibilities and interfaces</th></tr>
          </thead>
          <tbody>
            {architecture.modules.length ? architecture.modules.map((module) => (
              <tr key={module.name}>
                <td><strong>{module.name}</strong></td>
                <td>{module.layer}</td>
                <td>
                  {module.responsibilities}
                  {module.interfaces.length ? <p className="pdf-cell-note">Interfaces: {module.interfaces.join(", ")}</p> : null}
                </td>
              </tr>
            )) : (
              <tr><td colSpan={3}>No application modules captured.</td></tr>
            )}
          </tbody>
        </table>
      </section>

      <section className="pdf-section">
        <h2 className="pdf-section-title">Functional requirements</h2>
        <table className="pdf-table">
          <thead>
            <tr><th>ID</th><th>Requirement</th><th>Priority</th></tr>
          </thead>
          <tbody>
            {result.functionalRequirements.map((item) => (
              <tr key={item.id}>
                <td>{item.id}</td>
                <td><strong>{item.title}</strong><p className="pdf-cell-note">{item.description}</p></td>
                <td className="pdf-priority">{item.priority}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section className="pdf-section">
        <h2 className="pdf-section-title">Non-functional requirements</h2>
        <table className="pdf-table">
          <thead>
            <tr><th>ID</th><th>Category</th><th>Requirement</th><th>Target</th></tr>
          </thead>
          <tbody>
            {result.nonFunctionalRequirements.map((item) => (
              <tr key={item.id}>
                <td>{item.id}</td>
                <td>{item.category}</td>
                <td>{item.requirement}</td>
                <td>{item.target}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section className="pdf-section">
        <h2 className="pdf-section-title">Technology choices</h2>
        <table className="pdf-table">
          <thead>
            <tr><th>Layer</th><th>Technology</th><th>Rationale</th></tr>
          </thead>
          <tbody>
            {architecture.techStack.map((stack) => (
              <tr key={stack.layer}>
                <td><strong>{stack.layer}</strong></td>
                <td>{stack.choices.join(", ")}</td>
                <td>{stack.why}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section className="pdf-section">
        <h2 className="pdf-section-title">Integration points</h2>
        {architecture.integrationPoints.length ? (
          <ul className="pdf-list">
            {architecture.integrationPoints.map((item) => <li key={item}>{item}</li>)}
          </ul>
        ) : <p className="pdf-copy">No integration points captured.</p>}
      </section>

      <section className="pdf-section">
        <h2 className="pdf-section-title">Assumptions</h2>
        {result.assumptions.length ? (
          <ul className="pdf-list">
            {result.assumptions.map((item) => <li key={item}>{item}</li>)}
          </ul>
        ) : <p className="pdf-copy">No assumptions captured.</p>}
      </section>

      <section className="pdf-section pdf-approval">
        <h2 className="pdf-section-title">Approval</h2>
        {artifact ? (
          <>
            <p className="pdf-copy">{artifact.approvalNote || "This architecture package passed the human review gate."}</p>
            <p className="pdf-meta">Status: Approved for release</p>
          </>
        ) : (
          <p className="pdf-copy">Draft proposal. Human architecture review is required before approval.</p>
        )}
      </section>
    </article>
  );
}
